# RULER CWE（common words extraction）/ FWE（frequent words extraction）任务。
# RULER 官方格式：合成词表流（common ×30 / filler ×8 / uncommon ×3），问最高频词。
# 信号词散布全上下文（far+near 混合），是稀疏注意力的聚合型压力测试（与
# NIAH 检索型互补）。词表从 LongBench 语料抽取（101K 词种，真实英文词）。
# 评分（RULER 官方）：CWE = max(0, 命中common数 − 误报uncommon数)/10；
# FWE = 命中 frequent 数/3。
# 用法同 test_tli_ruler.py（RULER_SEED / RULER_TAG / RULER_N）。
import json
import os
import random
import re
import sys
import time
import warnings
from collections import Counter

sys.path.insert(0, "/home/wangyuanshuo02/sglang/python")
warnings.filterwarnings("ignore")

from sglang import Engine

MODEL = "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B"
DATA_DIR = "/home/wangyuanshuo02/datasets/LongBench/data"
TARGET_TOKENS = int(os.environ.get("NIAH_TOKENS", 32000))
N_PER_TASK = int(os.environ.get("RULER_N", 20))
OUT_JSON = "/home/wangyuanshuo02/sglang/tli_ruler_cwe_results.json"

# Qwen3 chat 格式 + assistant prefill 空 think 块（no-think 官方方式）。
# CWE/FWE 是聚合计数任务，thinking 链会吃满 max_new_tokens 也数不完。
QWEN_USER = (
    "<|im_start|>user\n{body}<|im_end|>\n"
    "<|im_start|>assistant\n<think>\n\n</think>\n\n"
)
CWE_Q = (
    "\nThe list above was generated by a random word generator. "
    "It contains ONLY the words shown, with no English grammar words. "
    "Count the occurrences and find the most frequent ones. "
    "What are the 10 most common words in the list above? "
    "The answer must be words that appear in the list. "
    "Answer with only the words, separated by commas."
)
FWE_Q = (
    "\nThe list above was generated by a random word generator. "
    "It contains ONLY the words shown, with no English grammar words. "
    "Count the occurrences and find the most frequent ones. "
    "What are the 3 most frequently used words in the list above? "
    "The answer must be words that appear in the list. "
    "Answer with only the words, separated by commas."
)


def build_vocab():
    """LongBench 语料中频真实英文词（避免 the/and 超高频与生僻词）。"""
    words = Counter()
    import glob

    for f in sorted(glob.glob(f"{DATA_DIR}/*.jsonl")):
        for l in open(f):
            r = json.loads(l)
            for w in re.findall(r"[a-z]{5,9}", (r.get("context") or "").lower()):
                words[w] += 1
            if sum(words.values()) > 3_000_000:
                break
        if sum(words.values()) > 3_000_000:
            break
    mid = [w for w, c in words.most_common() if 3 <= c <= 200]
    return mid


def make_word_stream(rng, vocab, n_target_words, n_common, common_freq,
                      n_uncommon, uncommon_freq, filler_freq):
    """合成词流：common×freq_high + uncommon×freq_low + filler×freq_mid，
    全部 shuffle。filler 频率取 8（30 > 8 > 3 频率沟清晰）。"""
    common = rng.sample(vocab, n_common + n_uncommon)
    c_words, u_words = common[:n_common], common[n_common:]
    stream = []
    for w in c_words:
        stream += [w] * common_freq
    for w in u_words:
        stream += [w] * uncommon_freq
    n_fill = max(0, (n_target_words - len(stream)) // filler_freq)
    used = set(c_words) | set(u_words)
    fillers = [w for w in rng.sample(vocab, min(n_fill * 2, len(vocab)))
               if w not in used][:n_fill]
    for w in fillers:
        stream += [w] * filler_freq
    rng.shuffle(stream)
    return " ".join(stream), c_words, u_words


def make_task_samples(tok, rng):
    vocab = build_vocab()
    print(f"[vocab] {len(vocab)} words")
    tasks = {}

    # ---- CWE：10 common ×30 / 10 uncommon ×3，问 10 个最高频词 ----
    samples = []
    for i in range(N_PER_TASK):
        # 32K token ≈ 21K 词（词均 ~1.5 token）；超配后 token 精确截断
        text, c_words, u_words = make_word_stream(
            rng, vocab, 22000, 10, 30, 10, 3, 8)
        enc = tok(text, add_special_tokens=False, return_offsets_mapping=True)
        if len(enc["input_ids"]) < TARGET_TOKENS + 256:
            continue
        cut = enc["offset_mapping"][TARGET_TOKENS - 1][1]
        # Qwen3 raw prompt 下 thinking 默认开启且 /no_think 软开关不生效
        # （无 chat template 解析）。手动拼 chat 格式 + assistant 开头
        # prefill 空 <think> 块 = Qwen3 官方 no-think 方式，直接出答案。
        prompt = QWEN_USER.format(body=text[:cut] + CWE_Q)
        samples.append({"common": c_words, "uncommon": u_words, "prompt": prompt})
    tasks["cwe"] = samples

    # ---- FWE：3 frequent ×30 / 10 low ×5，问 3 个最高频词 ----
    samples = []
    for i in range(N_PER_TASK):
        text, c_words, u_words = make_word_stream(
            rng, vocab, 22000, 3, 30, 10, 5, 8)
        enc = tok(text, add_special_tokens=False, return_offsets_mapping=True)
        if len(enc["input_ids"]) < TARGET_TOKENS + 256:
            continue
        cut = enc["offset_mapping"][TARGET_TOKENS - 1][1]
        prompt = QWEN_USER.format(body=text[:cut] + FWE_Q)
        samples.append({"common": c_words, "uncommon": u_words, "prompt": prompt})
    tasks["fwe"] = samples

    for name, ss in list(tasks.items()):
        fin = []
        for s in ss:
            n = len(tok(s["prompt"], add_special_tokens=False)["input_ids"])
            if n < 40960 - 256:
                s["prompt_tokens"] = n
                fin.append(s)
        tasks[name] = fin
    return tasks


def score_cwe(common, uncommon, out):
    """RULER 官方：(命中 common 数 − 误报 uncommon 数)/10，clamp ≥0。"""
    low = out.lower()
    hits = sum(1 for w in common if w in low)
    fp = sum(1 for w in uncommon if w in low)
    return max(0, hits - fp) / 10


def score_fwe(common, out):
    low = out.lower()
    return sum(1 for w in common if w in low) / 3


def main():
    backend = sys.argv[1] if len(sys.argv) > 1 else "tli"
    tag = f"cwefe_{backend}"
    if os.environ.get("RULER_TAG"):
        tag = os.environ["RULER_TAG"]
    rng = random.Random(int(os.environ.get("RULER_SEED", 1234)))

    from transformers import AutoTokenizer

    tok = AutoTokenizer.from_pretrained(MODEL, trust_remote_code=True)
    tasks = make_task_samples(tok, rng)
    for name, ss in tasks.items():
        print(f"[{tag}] {name}: {len(ss)} samples")

    kwargs = dict(
        model_path=MODEL,
        attention_backend=backend,
        dtype="bfloat16",
        device="cuda",
        mem_fraction_static=0.7,
        trust_remote_code=True,
        disable_radix_cache=True,
        watchdog_timeout=3600,
        cuda_graph_config={"decode": {"backend": "full", "bs": [1]}, "prefill": {"backend": "disabled"}},
    )
    t0 = time.time()
    eng = Engine(**kwargs)
    print(f"[{tag}] engine init {time.time() - t0:.1f}s")
    eng.generate(["warmup"], sampling_params={"temperature": 0.0, "max_new_tokens": 4})

    all_res = {}
    if os.path.exists(OUT_JSON):
        try:
            all_res = json.load(open(OUT_JSON))
        except Exception:
            all_res = {}

    task_results = {}
    for name, ss in tasks.items():
        prompts = [s["prompt"] for s in ss]
        t0 = time.time()
        outs = eng.generate(prompts, sampling_params={"temperature": 0.0, "max_new_tokens": 256})
        t_gen = time.time() - t0
        rows = []
        for s, o in zip(ss, outs):
            text = o["text"]
            if name == "cwe":
                sc = score_cwe(s["common"], s["uncommon"], text)
            else:
                sc = score_fwe(s["common"], text)
            rows.append({"score": round(sc, 3), "common": s["common"],
                         "uncommon": s["uncommon"], "out": text.strip()[:1500],
                         "prompt_tokens": s["prompt_tokens"]})
        avg = sum(r["score"] for r in rows) / max(1, len(rows))
        task_results[name] = {"score": round(avg, 3), "n": len(rows),
                              "gen_s": round(t_gen, 1), "samples": rows}
        print(f"[{tag}] {name}: avg partial score {avg:.3f}  (gen {t_gen:.1f}s)")
        sys.stdout.flush()

    all_res[tag] = task_results
    json.dump(all_res, open(OUT_JSON, "w"), indent=1)
    print(f"saved {OUT_JSON} [{tag}]")
    eng.shutdown()


if __name__ == "__main__":
    main()
