#!/bin/bash
cd /home/wangyuanshuo02/two-level-attention
set -e
echo '=== [screen mminmax a=0.375 b=0.375 $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task hotpotqa --method tli --e 0 --t 0929e72 --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.375 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method minmax  --pred_postfix _e72_mminmax 2>&1 | tail -2
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task musique --method tli --e 0 --t 0929e72 --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.375 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method minmax  --pred_postfix _e72_mminmax 2>&1 | tail -2
echo '=== [screen mavg a=0.125 b=0.375 $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task hotpotqa --method tli --e 0 --t 0929e72 --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg  --pred_postfix _e72_mavg 2>&1 | tail -2
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task musique --method tli --e 0 --t 0929e72 --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg  --pred_postfix _e72_mavg 2>&1 | tail -2
echo '=== [screen aavg a=0.125 b=0.25 $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task hotpotqa --method tli --e 0 --t 0929e72 --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.25 --tli_gamma 0.125 --tli_far_method avg --tli_near_method avg  --pred_postfix _e72_aavg 2>&1 | tail -2
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task musique --method tli --e 0 --t 0929e72 --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.25 --tli_gamma 0.125 --tli_far_method avg --tli_near_method avg  --pred_postfix _e72_aavg 2>&1 | tail -2
echo '=== [screen cavg a=0.125 b=0.375 $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task hotpotqa --method tli --e 0 --t 0929e72 --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --tli_enable_kmeans true --tli_far_select cluster --pred_postfix _e72_cavg 2>&1 | tail -2
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task musique --method tli --e 0 --t 0929e72 --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --tli_enable_kmeans true --tli_far_select cluster --pred_postfix _e72_cavg 2>&1 | tail -2
echo "SCREEN ALL DONE"
