#!/bin/bash
cd /home/wangyuanshuo02/two-level-attention
echo '=== [full1 mavg multi_news $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=1 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task multi_news --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full1 mavg triviaqa $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=1 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task triviaqa --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full1 mavg lcc $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=1 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task lcc --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full1 mavg repobench-p $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=1 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task repobench-p --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full1 mavg musique $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=1 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task musique --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full1 mavg 2wikimqa $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=1 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task 2wikimqa --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full1 mavg passage_retrieval_en $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=1 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task passage_retrieval_en --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo "FULL GPU1 DONE"
