#!/bin/bash
cd /home/wangyuanshuo02/two-level-attention
echo '=== [full0 mavg narrativeqa $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task narrativeqa --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full0 mavg gov_report $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task gov_report --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full0 mavg qmsum $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task qmsum --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full0 mavg qasper $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task qasper --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full0 mavg multifieldqa_en $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task multifieldqa_en --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo '=== [full0 mavg hotpotqa $(date +%H:%M:%S)] ==='
CUDA_VISIBLE_DEVICES=0 python -u -m benchmark.LongBench.pred --model Qwen3-8B --model_path /mnt/dolphinfs/ssd_pool/docker/user/hadoop-mlp-ckpt/sunyueqing/Qwen3-8B --task hotpotqa --method tli --e 0 --t 0929e72f --dataset-path /home/wangyuanshuo02/datasets/LongBench/data --config-path benchmark/LongBench/config --output-dir exp/results_longbench/Qwen3-8B --tia_level1_topk 128 --tia_level2_topk 1024 --tia_level2_cmp_ratio 4 --tli_enable_layer_skip false --tli_alpha 0.125 --tli_beta 0.375 --tli_gamma 0.125 --tli_far_method minmax --tli_near_method avg --pred_postfix _e72f_mavg 2>&1 | tail -2
echo "FULL GPU0 DONE"
